### ISSUE TITLE
With multiple forwarded ports, one gets lost

### ISSUE THREAD

**Issue by mattrixman** [sorend/sshconf#1]
Here is an ssh config file:

    Host foo
        HostName foo.bar.baz
        User me
        IdentityFile /home/me/.ssh/work_rsa
        IdentitiesOnly yes
        LocalForward 10002 127.0.0.1:3306 # mysql
        LocalForward 58999 127.0.0.1:8999 # the_app

Here is how sshconf sees it:
    
    {'hostname': 'foo.bar.baz',
     'identitiesonly': 'yes',
     'identityfile': '/home/me/.ssh/work_rsa',
     'localforward': '58999 127.0.0.1:8999',
     'user': 'me'}

Note the absence of the first LocalForward enty. Perhaps sshconf should detect multiple declarations and store them as a list?

**Comment by sorend** [comment]
Hi. Thanks for your keen observation. It has been fixed in 0.1.0
BR, Søren
