### ISSUE TITLE
Add entry to beginning of the file

### ISSUE THREAD

**Issue by njrafi** [sorend/sshconf#16]
I have a config file similar to this
```
Host host1
...

Host host2
...

Host *
...
```

I want to add host3. But if host3 is added at the end, the * config will be used which is not intended. It would be good to have an option to add the entry to beginning of the file.

**Comment by sorend** [comment]
I have added the `before_host` arg to the `add()` method. Let me know if it resolves the issue. 

Thanks, Soren
