### ISSUE TITLE
how to add multi property

### ISSUE THREAD

**Issue by owenstake** [sorend/sshconf#18]
result ssh config file. we will have multi "RemoteForward" property
```bash
Host 192.168.110.4
  ProxyCommand nc -X 5 -x 172.26.176.1:10832 %h %p
  RemoteForward localhost:3322  localhost:22
  RemoteForward localhost:10809 172.26.176.1:10809
```

**Comment by sorend** [comment]
It's possible by setting `c.set("thehost", RemoteForward=["forward:1 forward:2","forward:3 forward:4"])`

I have updated README with an example.

BR,
Soren
