### ISSUE TITLE
Treating name host as a list to support alias

### ISSUE THREAD

**Issue by poofyteddy** [sorend/sshconf#2]
Hello,
I wish to be able to give multiple name to my config (see https://makandracards.com/makandra/1242-defining-host-aliases-in-your-ssh-config)

Right now i can put multiple name with space : 
```
c = sshconf.empty_ssh_config()
c.add("svu svu.local appname", Hostname="ssh.svu.local", User="teachmca", Port=22)
```
But if i want to do anything to this config afterward, i have to give the full name for it to work : 

> c.host("svu")
> {}
>  c.host("svu svu.local appname")
> {'hostname': 'ssh.svu.local', 'user': 'teachmca', 'port': 22}
> 

It would help a lot if the name could be treated as a list of element, and if calling any of theme could work.

Thank's for the good work !

**Comment by sorend** [comment]
Hi, it should be fairly easy to implement this yourself:

`host_with_aliases = [ x for x in c.hosts() if "myalias" in x.split() ][0]
host = c.host(host_with_aliases)`
