### ISSUE TITLE
Invalid package metadata

### ISSUE THREAD

**Issue by konserw** [sorend/sshconf#8]
Also
![image](https://user-images.githubusercontent.com/2083653/87946772-21973f00-caab-11ea-973a-f78744f2567a.png)

_Originally posted by @aviadra in https://github.com/sorend/sshconf/issues/5#issuecomment-661060807_

**Comment by konserw** [comment]
Could you please fix this problem? I've been also hit by this and it's breaking my poetry configuration

**Comment by addisonklinke** [comment]
Also having this problem. The only way to install currently is to manually download the tarball from PyPI and pass that to `pip`

**Comment by aviadra** [comment]
actually it installs just fine for me, but doesn't update the version pip
sees, so it always thinks it's not installed.

**Comment by sorend** [comment]
I hope it has been fixed with 0.2.2, available from pypi now.

Please let me know if you still experience the problem.

BR,
Søren
